language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tordanf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tordanf/react-test npm test

after_success:
  - docker build -t tordanf/multi-client ./client
  - docker build -t tordanf/multi-nginx ./nginx
  - docker build -t tordanf/multi-server ./server
  - docker build -t tordanf/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those iamges an dpush them to docker hub
  - docker push tordanf/multi-client
  - docker push tordanf/multi-nginx
  - docker push tordanf/multi-server
  - docker push tordanf/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: multiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-248183079538
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
